#!/bin/sh
# fadfetch - System Information Tool for FAD Linux

C_LOGO="\033[1;36m"
C_LABEL="\033[1;37m" 
C_TEXT="\033[0m"

USER=$(whoami 2>/dev/null || echo "root")
HOSTNAME=$(cat /etc/hostname 2>/dev/null || echo "fadlinux")
OS="FAD Linux"
KERNEL=$(uname -r 2>/dev/null || echo "Unknown")
ARCH=$(uname -m 2>/dev/null || echo "Unknown")
SHELL_NAME=$(basename "$SHELL" 2>/dev/null || echo "bash")

if [ -f /proc/uptime ]; then
    UPTIME_SEC=$(awk '{print int($1)}' /proc/uptime)
    UPTIME_H=$((UPTIME_SEC / 3600))
    UPTIME_M=$(( (UPTIME_SEC % 3600) / 60 ))
    UPTIME="${UPTIME_H}h ${UPTIME_M}m"
else
    UPTIME="Unknown"
fi

if [ -d "/var/lib/fadev/manifests" ]; then
    PKGS=$(ls -1 /var/lib/fadev/manifests 2>/dev/null | wc -l)
else
    PKGS=0
fi

#
if [ -f /proc/meminfo ]; then
    MEM_TOTAL=$(awk '/MemTotal:/ {print int($2/1024)}' /proc/meminfo)
    MEM_FREE=$(awk '/MemAvailable:/ {print int($2/1024)}' /proc/meminfo)
    if [ -z "$MEM_FREE" ]; then
        MEM_FREE=$(awk '/MemFree:/ {print int($2/1024)}' /proc/meminfo)
    fi
    MEM_USED=$((MEM_TOTAL - MEM_FREE))
    MEMORY="${MEM_USED}MiB / ${MEM_TOTAL}MiB"
else
    MEMORY="Unknown"
fi


echo -e ""
echo -e "${C_LOGO}   FFFFFFFFFFFFF${C_TEXT}     ${C_LOGO}${USER}${C_TEXT}@${C_LOGO}${HOSTNAME}${C_TEXT}"
echo -e "${C_LOGO}   FF           ${C_TEXT}     -------------------"
echo -e "${C_LOGO}   FF           ${C_TEXT}     ${C_LABEL}OS:${C_TEXT} $OS $ARCH"
echo -e "${C_LOGO}   FFFFFFFF     ${C_TEXT}     ${C_LABEL}Kernel:${C_TEXT} $KERNEL"
echo -e "${C_LOGO}   FF           ${C_TEXT}     ${C_LABEL}Uptime:${C_TEXT} $UPTIME"
echo -e "${C_LOGO}   FF           ${C_TEXT}     ${C_LABEL}Packages:${C_TEXT} $PKGS (fadev)"
echo -e "${C_LOGO}   FF           ${C_TEXT}     ${C_LABEL}Shell:${C_TEXT} $SHELL_NAME"
echo -e "${C_LOGO}                ${C_TEXT}     ${C_LABEL}Memory:${C_TEXT} $MEMORY"
echo -e ""

echo -e "   \033[41m  \033[42m  \033[43m  \033[44m  \033[45m  \033[46m  \033[47m  \033[0m"
echo -e ""