name: Build FAD Linux Monolithic Rootfs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-os:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Rootfs inside Container
        run: |
          docker build -t fad-builder .

          docker run --name builder-container fad-builder
          
          docker cp builder-container:/build/rootfs ./rootfs
          
          # Пакуем в архив для артефактов
          tar -czf fad_rootfs.tar.gz -C rootfs .

      - name: Upload Rootfs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fad-linux-rootfs
          path: fad_rootfs.tar.gz